server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password: 123456
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1